version: 2
updates:
  # Enable version updates for npm dependencies
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
    open-pull-requests-limit: 10
    reviewers:
      - 'robbeverhelst'
    assignees:
      - 'robbeverhelst'
    commit-message:
      prefix: 'deps'
      include: 'scope'
    labels:
      - 'dependencies'
      - 'automated'
    # Group minor and patch updates together
    groups:
      development-dependencies:
        patterns:
          - '@types/*'
          - 'eslint*'
          - 'prettier*'
          - 'typescript'
          - '@typescript-eslint/*'
        update-types:
          - 'minor'
          - 'patch'
      production-dependencies:
        patterns:
          - 'next'
          - 'react*'
          - '@radix-ui/*'
          - 'lucide-react'
          - 'clsx'
          - 'tailwindcss*'
          - 'observation-js'
        update-types:
          - 'minor'
          - 'patch'

  # Enable version updates for GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
    open-pull-requests-limit: 5
    reviewers:
      - 'robbeverhelst'
    assignees:
      - 'robbeverhelst'
    commit-message:
      prefix: 'ci'
      include: 'scope'
    labels:
      - 'github-actions'
      - 'automated'
